# Use this to run MySQL in Docker
services:
  mysql:
    image: mysql:8.0
    container_name: homeworks_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homeworks
      MYSQL_USER: homeworks_user
      MYSQL_PASSWORD: homeworks_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: